### ISSUE TITLE
Charset range

### ISSUE THREAD

**Issue by sgalal** [LisaHuang2017/noto-sans-nushu#1]
Thanks for this great project!

Besides U+1B170-U+1B2FF currently stated in the project, there is also Nushu Iteration Mark U+16FE1 (𖿡), in the Ideographic Symbols and Punctuation block.

**Comment by LisaHuang2017** [comment]
Thanks for letting me know about U+16FE1! I used the charset from Unicode's updated table for Nüshu, which went from U+1B170 to U+1B2FF. I didn't know that there was other Nüshu-related glyphs outside this range.
The project is still in progress, there will be updates regularly these next days! 😁

**Comment by LisaHuang2017** [comment]
Glyph u16FE1 added in [this](https://github.com/LisaHuang2017/noto-sans-nushu/commit/27ed8efb5bf38077aa3fc93eb5b47273871e8095) commit.
This issue can be closed.
