### ISSUE TITLE
OFL license references another project

### ISSUE THREAD

**Issue by eliheuer** [LisaHuang2017/noto-sans-nushu#6]
From commit 2264b46 to af1b338 the license file references another project. This might be a mistake and could cause confusion.

OFL.txt currently reads:
```
Copyright 2019 The Recursive Project Authors (info@arrowtype.com)
```
My expectation was:
```
Copyright 2019 The Noto Sans Nüshu Project Authors (https://github.com/LisaHuang2017/noto-sans-nushu)
```
There might be some reason for this I don't understand, just something I noticed while looking at the repository.

**Comment by arrowtype** [comment]
Thanks for catching this, Eli. The reason was too quick a copy-paste of the file. :)
